name: Weaveworks Github action
author: weave.works
description: Enforce cloud security and best practices at the build and deployment time.
inputs:
  path:
    description: path to resources kustomization
    required: true
    
  helm-values-file:
    description: path to helm values file
    required: false
  
  policies-path:
    description: path to policies kustomization
    required: true

  policies-helm-values-file:
    description: path to policies helm values file
    required: false

  repository:
    description: repository
    default: ${{ github.repository }}
    required: false

  branch:
    description: branch name
    default: ${{ github.head_ref || github.ref }}
    required: false
  
  commit:
    description: commit SHA
    default: ${{ github.event.pull_request.head.sha || github.sha }}
    required: false

  token:
    description: github token
    default: ${{ github.token }}
    required: false

  sarif-file:
    description: export result in sarif format
    required: false
 
  sast-file:
    description: export result in sast format
    required: false
  
  json-file:
    description: export result in json format
    required: false

  remediate:
    description: auto remediate resources if possible
    required: false

  generate-git-report:
    description: auto remediate resources if possible
    default: "true"
    required: false

  no-exit-error:
    description: exist with no error
    required: false

branding:
  color: blue
  icon: shield

runs:
  using: docker
  image: docker://magalixcorp/weave-validator:dev
  args:
    - weave-validator
    - --path 
    - ${{ inputs.path }}
    - --helm-values-file
    - ${{ inputs.helm-values-file }}
    - --policies-path
    - ${{ inputs.policies-path }}
    - --policies-helm-values-file
    - ${{ inputs.policies-helm-values-file }}
    - --git-repo-provider
    - github
    - --git-repo-url
    - ${{ inputs.repository }}
    - --git-repo-token
    - ${{ inputs.token }}
    - --git-repo-branch 
    - ${{ inputs.branch }}
    - --git-repo-sha
    - ${{ inputs.commit }}
    - --sarif
    - ${{ inputs.sarif-file }}
    - --sast
    - ${{ inputs.sast-file }}
    - --json
    - ${{ inputs.json-file }}
    - ${{ inputs.remediate == 'true' && '--remediate' || '' }}
    - ${{ inputs.generate-git-report == 'true' && '--generate-git-report' || '' }}
    - ${{ inputs.no-exit-error == 'true' && '--no-exit-error' || '' }}